import { makeStyles, tokens } from "@fluentui/react-components";

export const useStyles = makeStyles({
  root: {
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    height: "fit-content",
    width: "fit-content",
    minHeight: "100px",
    minWidth: "280px",
    maxWidth: "320px",
    maxHeight: "520px",
  },
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    padding: "14px 16px 10px",
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    userSelect: "none",
  },
  headerLeft: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  appName: {
    fontSize: tokens.fontSizeBase400,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorNeutralForeground1,
  },
  nodeName: {
    fontSize: tokens.fontSizeBase100,
    color: tokens.colorNeutralForeground3,
  },
  closeBtn: {
    minWidth: "auto",
    padding: "4px",
    color: tokens.colorNeutralForeground3,
  },
  content: {
    flex: "1 1 auto",
    display: "flex",
    flexDirection: "column",
    padding: "4px 0",
    overflowY: "auto",
    minHeight: 0,
  },
  sectionLabel: {
    fontSize: tokens.fontSizeBase100,
    fontWeight: tokens.fontWeightSemibold,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: tokens.colorNeutralForeground4,
    padding: "8px 16px 4px",
    display: "block",
  },
  statusRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 16px",
  },
  statusText: {
    display: "flex",
    flexDirection: "column",
    gap: "1px",
    flex: 1,
  },
  statusLabel: {
    fontSize: tokens.fontSizeBase300,
    fontWeight: tokens.fontWeightMedium,
    color: tokens.colorNeutralForeground1,
  },
  statusSub: {
    fontSize: tokens.fontSizeBase100,
    color: tokens.colorNeutralForeground3,
  },
  toggleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "4px 16px",
  },
  toggleLabel: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: tokens.fontSizeBase300,
    color: tokens.colorNeutralForeground1,
  },
  subControl: {
    padding: "2px 16px 8px 40px",
  },
  dropdown: {
    width: "80%",
  },
  dropdownPopup: {
    backgroundColor: tokens.colorNeutralBackground2,
  },
  actionRow: {
    padding: "3px 16px",
  },
  actionBtn: {
    width: "100%",
    justifyContent: "flex-start",
    backgroundColor: tokens.colorNeutralBackground3,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    borderRadius: tokens.borderRadiusMedium,
    padding: "8px 12px",
    color: tokens.colorNeutralForeground1,
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightMedium,
  },
  quitBtn: {
    width: "100%",
    justifyContent: "flex-start",
    backgroundColor: tokens.colorPaletteRedBackground1,
    border: `1px solid ${tokens.colorPaletteRedForeground1}`,
    borderRadius: tokens.borderRadiusMedium,
    padding: "8px 12px",
    color: tokens.colorPaletteRedForeground1,
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightMedium,
  },
  footer: {
    padding: "8px 16px 12px",
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  dot: {
    width: "8px",
    height: "8px",
    borderRadius: tokens.borderRadiusCircular,
    flexShrink: 0,
    transition: `background ${tokens.durationFaster}`,
  },
});
